### ISSUE TITLE
error with dustmasker and centrifuge-download

### ISSUE THREAD

**Issue by NichKu** [XWangLabTHU/cfDNApipe#7]
Hello

Great tools, thanks a lot!

I encountered an issue with the centrifuge-download command in virusGenomeCheck with the flag -m.

The error is:

Downloading ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/viral/assembly_summary.txt ...
_: line 28: dustmasker: command not found
_: line 28: dustmasker: command not found
Progress : [----------------------------------------] 0% 2/11357_: line 28: dustmasker: command not found.

...

Progress : [#######################################-] 99% 11356/11357_: line 28: dustmasker: command not found
Progress : [########################################] 100% 11357/11357

Exits after attempting to download all viral genomes but the files have a size of 0kb.

Best,
Nich

**Comment by NichKu** [comment]
solved it. 
Maybe I've missed it but if not, you might consider adding a note about the environment_20210406.yml file where blast is listed.

**Comment by Honchkrow** [comment]
Hi @NichKu ,
  Sorry for late response. I will test the error and update a new version environment file.

best,
Honchkrow
