### ISSUE TITLE
variant calling in WGS cfDNA from cancer patients

### ISSUE THREAD

**Issue by egenomics** [XWangLabTHU/cfDNApipe#9]
Hi,
I am trying to generate some variant calling data for several samples obtained from cfDNA patients with lung cancer, with known mutations. 
I am able to run the first part of the pipeline after downloading the reference genome (hg38) and executing:
```
from cfDNApipe import *

pipeConfigure(
    threads=16,
    genome="hg38",
    refdir=r"/well/buck/users/xhs232/references/cfdnapipe",
    outdir=r"/well/buck/users/xhs232/analysis/cfdna_fragmentomics",
    data="WGS",
    type="paired",
    build=True,
    JavaMem="10g",
)

res = cfDNAWGS(
    inputFolder=r"/well/buck/users/xhs232/data_hcb/longwood_fastqs",
    idAdapter=True,
    rmAdapter=True,
    dudup=True,
    CNV=True,
    armCNV=True,
    fragProfile=True,
    verbose=False,
    report=True,
)

```
However, looking at the example code I fail to run and/or understand the following bit of code:

```
# check SNV reference path
Configure.snvRefCheck(folder="/well/buck/users/xhs232/references/cfdnapipe", build=True)

```
What exactly is trying to do this bit of code? I get the following error, as it can't locate such a file and it was not downloaded using the reference build script.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/well/buck/users/xhs232/conda/envs/cfDNApipe/lib/python3.6/site-packages/cfDNApipe/Configure.py", line 681, in snvRefCheck
    raise commonError("SNV reference files are missing, please check reference files!")
cfDNApipe.cfDNA_utils.commonError: SNV reference files are missing, please check reference files!

```

Thanks in advance,
JL

**Comment by egenomics** [comment]
Looking at the inner code it looks like the files needed are the following:

                    "1": os.path.join(folder, "1000G_omni2.5.hg38.vcf"),
                    "2": os.path.join(folder, "1000G_phase1.snps.high_confidence.hg38.vcf"),
                    "3": os.path.join(folder, "dbsnp_146.hg38.vcf"),
                    "4": os.path.join(folder, "hapmap_3.3.hg38.vcf"),
                    "5": os.path.join(folder, "Mills_and_1000G_gold_standard.indels.hg38.vcf"),
                    "6": os.path.join(folder, "af-only-gnomad.hg38.vcf"),
                    "7": os.path.join(folder, "small_exac_common_3_hg38.SNP_biallelic.vcf"),
                    "8": os.path.join(folder, "somatic-hg38_1000g_pon.hg38.vcf"),

I have managed to download the first 5 from the ftp.broadinstitute and decompress them from *.vcf.gz to .vcf.

I have also found number 6:
wget https://www.bcgsc.ca/downloads/morinlab/reference/af-only-gnomad.hg38.vcf.gz

File 7 I obtained it from here:
https://console.cloud.google.com/storage/browser/gatk-best-practices/somatic-hg38;tab=objects?pli=1&prefix=&forceOnObjectsSortingFiltering=false

Again, had to decompress it.

I am not sure where to obtain number 8, there is a similar file here (1000g_pon.hg38.vcf.gz), but I am not sure is the correct one:
https://console.cloud.google.com/storage/browser/gatk-best-practices/somatic-hg38;tab=objects?prefix=&forceOnObjectsSortingFiltering=false

I believe the difficulty of generating the reference files for SNP calling is preventing a lot of people from using your pipeline. Perhaps you can enhance the documentation or provide an automatic way of generating this part.

JL

**Comment by Honchkrow** [comment]
Hello @egenomics,
  Sorry for late response. The file 8 can be accessed from this url: https://storage.googleapis.com/gatk-best-practices/somatic-hg38/af-only-gnomad.hg38.vcf.gz

  I will collect all the refeerence file and upload them to google cloud.

  thanks for using cfDNApipe. If you have any problems, please let me known and I will try my best to help you.

Honchkrow
